# Generated by Django 5.2.15 on 2026-06-28 07:12

from django.db import migrations, models


def backfill_patient_uhids(apps, schema_editor):
    Patient = apps.get_model('clinic', 'Patient')
    for patient in Patient.objects.all():
        if not patient.uhid:
            Patient.objects.filter(pk=patient.pk).update(uhid=f'UHID{patient.pk:06d}')


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uhid',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_patient_uhids, migrations.RunPython.noop),
    ]
